name: WordPress.org plugin asset/readme update
on:
  push:
    paths:
    - "readme.txt"
    - ".wordpress-org/*"
    branches:
    - "master"
jobs:
  trunk:
    name: Plugin asset/readme update
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64
    steps:
      - uses: runs-on/action@v2
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
